# Generated by Django 4.2.21 on 2025-06-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('train_type', models.CharField(max_length=50)),
                ('owning_zone', models.CharField(max_length=100)),
                ('from_point', models.CharField(max_length=100)),
                ('to_point', models.CharField(max_length=100)),
            ],
        ),
    ]
