# Generated by Django 4.2.21 on 2025-06-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_department_reportdata_report_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JabalpurOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10)),
                ('train_name', models.CharField(max_length=100)),
                ('train_type', models.CharField(max_length=20)),
                ('owning_zone', models.CharField(max_length=50)),
                ('from_point', models.CharField(max_length=50)),
                ('to_point', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RailMadadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('complaint_description', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='manual',
            new_name='is_manual',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default='2025-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
