# Generated by Django 4.2.21 on 2025-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_dataentry_jabalpuroperation_railmadadreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
