# Generated by Django 4.2.21 on 2025-06-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_report_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportData',
        ),
        migrations.AlterField(
            model_name='report',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
    ]
