# Generated by Django 4.2.21 on 2025-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_delete_reportdata_alter_report_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('last_updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_manual',
        ),
        migrations.AddField(
            model_name='report',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
