# Generated by Django 4.2.21 on 2025-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_reportdata_remove_report_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdata',
            old_name='report_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='last_updated_at',
        ),
        migrations.AddField(
            model_name='reportdata',
            name='data1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='data2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='data3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
