# Generated by Django 4.2.21 on 2025-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_rename_report_name_reportdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railmadadreport',
            name='ref_no',
            field=models.CharField(max_length=50),
        ),
    ]
