# Generated by Django 4.2.21 on 2025-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_railmadadreport_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeBasicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20)),
                ('train_name', models.CharField(max_length=100)),
                ('train_type', models.CharField(max_length=50)),
                ('owning_zone', models.CharField(max_length=100)),
                ('from_point', models.CharField(max_length=100)),
                ('to_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatsMonthlyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_trains', models.IntegerField()),
                ('late_trains', models.IntegerField()),
                ('maintenance_done', models.IntegerField()),
            ],
        ),
    ]
